export const tabs = [
  {
    label: "Proctology",
    links: [
      { label: "Piles Treatment", link: "https://mediend.com/piles-surgery/" },
      { label: "Fistula Treatment", link: "" },
      { label: "Fissure Treatment", link: "" },
      { label: "Pilonidal Sinus Treatment", link: "" },
      { label: "Proctology", link: "" },
    ],
  },
  {
    label: "Laparoscopy",
    links: [
      { label: "Hernia Treatment", link: "" },
      { label: "Gallstone Treatment", link: "" },
      { label: "Appendicitis", link: "" },
      { label: "Inguinal Hernia Treatment", link: "" },
      { label: "Umbilical Hernia Treatment", link: "" },
    ],
  },
  {
    label: "Gynaecology",
    links: [
      { label: "MTP", link: "" },
      { label: "Uterus Removal", link: "" },
    ],
  },
  {
    label: "ENT",
    links: [
      { label: "Tympanoplasty", link: "" },
      { label: "Adenoidectomy", link: "" },
      { label: "Sinus Treatment", link: "" },
      { label: "Mastoidectomy", link: "" },
      { label: "Throat Surgery", link: "" },
      { label: "Ear Surgery", link: "" },
      { label: "Vocal Cord Polyps", link: "" },
      { label: "Nasal Polyps", link: "" },
      { label: "Turbinate Reduction", link: "" },
    ],
  },
  {
    label: "Urology",
    links: [
      { label: "Circumcision", link: "" },
      { label: "Stapler Circumcision", link: "" },
      { label: "Kidney Stones Treatment", link: "" },
      { label: "Hydrocele", link: "" },
      { label: "ESWL", link: "" },
      { label: "RIRS", link: "" },
      { label: "PCNL", link: "" },
      { label: "URSL", link: "" },
      { label: "Enlarged Prostate", link: "" },
    ],
  },

  {
    label: "Vascular",
    links: [
      { label: "Varicose Veins Treatment", link: "" },
      { label: "Varicocele Treatment", link: "" },
      { label: "DVT Treatment", link: "" },
      { label: "Diabetic Foot Ulcer Treatment", link: "" },
      { label: "Uterine Fibroids", link: "" },
    ],
  },
  {
    label: "Aesthetics",
    links: [
      { label: "Gynecomastia", link: "" },
      { label: "Gynecomastia", link: "" },
      { label: "Lipoma Surgery", link: "" },
      { label: "Breast Lift Surgery", link: "" },
      { label: "Sebaceous Cyst Surgery", link: "" },
      { label: "Rhinoplasty", link: "" },
      { label: "Breast Augmentation Surgery", link: "" },
      { label: "Axillary Breast", link: "" },
      { label: "Tummy Tuck", link: "" },
      { label: "Breast Lump", link: "" },
      { label: "Breast Reduction", link: "" },
      { label: "Double Chin", link: "" },
      { label: "Buccal Fat", link: "" },
      { label: "Earlobe Repair", link: "" },
      { label: "Blepharoplasty", link: "" },
      { label: "Beard Transplant", link: "" },
      { label: "Cleft Lip", link: "" },
    ],
  },

  {
    label: "Orthopedics",
    links: [
      { label: "Knee Replacement", link: "" },
      { label: "Carpal Tunnel Syndrome", link: "" },
      { label: "ACL Tear Treatment", link: "" },
      { label: "ProcMeniscus Tear Treatmenttology", link: "" },
      { label: "Hip Replacement Surgery", link: "" },
      { label: "Spine Surgery", link: "" },
      { label: "Shoulder Dislocation", link: "" },
      { label: "Shoulder Replacement", link: "" },
    ],
  },

  {
    label: "Ophthalmology",
    links: [
      { label: "Lasik Eye Surgery", link: "" },
      { label: "Cataract Surgery", link: "" },
      { label: "Retinal Detachment", link: "" },
      { label: "Glaucoma Treatment", link: "" },
      { label: "Squint Surgery", link: "" },
      { label: "Diabetic Retinopathy", link: "" },
      { label: "Vitrectomy", link: "" },
      { label: "PRK Lasik", link: "" },
      { label: "SMILE Lasik surgery", link: "" },
      { label: "FEMTO Lasik surgery", link: "" },
      { label: "ICL surgery", link: "" },
      { label: "Contoura Vision", link: "" },
      { label: "Phaco Surgery", link: "" },
    ],
  },
  {
    label: "Weight Loss",
    links: [
      { label: "Bariatric Surgery", link: "" },
      { label: "SPATZ intragastric balloon", link: "" },
      { label: "Weightloss Surge", link: "" },
    ],
  },
];
